import { v4 as uuidv4 } from "uuid";

//By adding the return type string to the function, you indicate that the function returns a string, which is the type of the unique ID generated by uuidv4
export const getUniqueID = (): string => {
    return uuidv4();
};

// now it can be used in any component
